import { Transaction, Truck, MaintenanceAlert } from './types';

export const INITIAL_TRUCKS: Truck[] = [
  {
    placa: 'TORK-3A45',
    modelo: 'Volvo FH 540 (Trator)',
    motorista: 'Carlos Alberto Menezes',
    statusDocumento: 'Vencendo',
    dataVencimentoIPVA: '2026-06-15',
    dataVencimentoSeguro: '2026-08-20',
    proximaManutencaoKm: 120000,
    kmAtual: 118450,
  },
  {
    placa: 'TORK-8B90',
    modelo: 'Scania R 450 (Câmara Fria)',
    motorista: 'Sebastião Silva Rodrigues',
    statusDocumento: 'Regular',
    dataVencimentoIPVA: '2026-11-10',
    dataVencimentoSeguro: '2026-06-05',
    proximaManutencaoKm: 85000,
    kmAtual: 84900, // Very close to maintenance limit!
  },
  {
    placa: 'TORK-5C12',
    modelo: 'M-Benz Actros 2651',
    motorista: 'Marcos Vinícius Costa',
    statusDocumento: 'Vencido',
    dataVencimentoIPVA: '2026-05-10', // Vencido
    dataVencimentoSeguro: '2026-12-05',
    proximaManutencaoKm: 210000,
    kmAtual: 198000,
  },
  {
    placa: 'TORK-9D78',
    modelo: 'DAF XF 530 (Graneleiro)',
    motorista: 'Adilson de Souza Filho',
    statusDocumento: 'Regular',
    dataVencimentoIPVA: '2026-09-30',
    dataVencimentoSeguro: '2026-10-15',
    proximaManutencaoKm: 150000,
    kmAtual: 132000,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // TORK-3A45 Transactions
  {
    id: 'tx-1',
    data: '2026-05-10',
    placa: 'TORK-3A45',
    categoria: 'Frete (Entrada)',
    empresaFavorecido: 'Suzano S.A.',
    descricaoHistorico: 'Frete Celulose - CTE 99423',
    numDocumento: '99423',
    tipo: 'Entrada',
    valor: 18500.00,
    status: 'Pago',
  },
  {
    id: 'tx-2',
    data: '2026-05-12',
    placa: 'TORK-3A45',
    categoria: 'Combustível',
    empresaFavorecido: 'Posto Iccar Rodo',
    descricaoHistorico: 'Abastecimento 450L Diesel S10',
    numDocumento: 'NF-8422',
    tipo: 'Saída',
    valor: 2655.00,
    status: 'Pago',
  },
  {
    id: 'tx-3',
    data: '2026-05-15',
    placa: 'TORK-3A45',
    categoria: 'Financiamento',
    empresaFavorecido: 'Banco Itaú',
    descricaoHistorico: 'Parcela CDC Volvo 18/36',
    numDocumento: 'IT-9321',
    tipo: 'Saída',
    valor: 5400.00,
    status: 'Pago',
  },
  {
    id: 'tx-4',
    data: '2026-05-20',
    placa: 'TORK-3A45',
    categoria: 'Seguros',
    empresaFavorecido: 'Allianz Seguros',
    descricaoHistorico: 'Parcela de Seguro Mensal',
    tipo: 'Saída',
    valor: 1100.00,
    status: 'Pago',
  },
  {
    id: 'tx-5',
    data: '2026-05-25',
    placa: 'TORK-3A45',
    categoria: 'Salários/Diárias',
    empresaFavorecido: 'Carlos Alberto Menezes',
    descricaoHistorico: 'Adiantamento de Diária de Viagem',
    tipo: 'Saída',
    valor: 1200.00,
    status: 'Pago',
  },

  // TORK-8B90 Transactions
  {
    id: 'tx-6',
    data: '2026-05-11',
    placa: 'TORK-8B90',
    categoria: 'Frete (Entrada)',
    empresaFavorecido: 'Delta Máquinas Ltda',
    descricaoHistorico: 'Frete Implementos Agrícolas - CTE 99450',
    numDocumento: '99450',
    tipo: 'Entrada',
    valor: 24500.00,
    status: 'Pago',
  },
  {
    id: 'tx-7',
    data: '2026-05-14',
    placa: 'TORK-8B90',
    categoria: 'Combustível',
    empresaFavorecido: 'Posto Iccar Rodo',
    descricaoHistorico: 'Abastecimento 550L Diesel S10',
    numDocumento: 'NF-8490',
    tipo: 'Saída',
    valor: 3245.00,
    status: 'Pago',
  },
  {
    id: 'tx-8',
    data: '2026-05-18',
    placa: 'TORK-8B90',
    categoria: 'Manutenção',
    empresaFavorecido: 'Mecânica Roda Gigante',
    descricaoHistorico: 'Alinhamento e Balanceamento Completo',
    numDocumento: 'REC-301',
    tipo: 'Saída',
    valor: 1800.00,
    status: 'Pago',
  },
  {
    id: 'tx-9',
    data: '2026-05-20',
    placa: 'TORK-8B90',
    categoria: 'Financiamento',
    empresaFavorecido: 'Banco Itaú',
    descricaoHistorico: 'Parcela CDC Scania R450 12/48',
    tipo: 'Saída',
    valor: 6100.00,
    status: 'Pago',
  },
  {
    id: 'tx-10',
    data: '2026-05-27',
    placa: 'TORK-8B90',
    categoria: 'Outros',
    empresaFavorecido: 'Sascar Rastreamento',
    descricaoHistorico: 'Mensalidade Rastreamento de Frota',
    tipo: 'Saída',
    valor: 180.00,
    status: 'Pago',
  },

  // TORK-5C12 Transactions
  {
    id: 'tx-11',
    data: '2026-05-08',
    placa: 'TORK-5C12',
    categoria: 'Frete (Entrada)',
    empresaFavorecido: 'Suzano S.A.',
    descricaoHistorico: 'Frete Bobinas Papel - CTE 99310',
    numDocumento: '99310',
    tipo: 'Entrada',
    valor: 15200.00,
    status: 'Pago',
  },
  {
    id: 'tx-12',
    data: '2026-05-15',
    placa: 'TORK-5C12',
    categoria: 'Financiamento',
    empresaFavorecido: 'Banco Itaú',
    descricaoHistorico: 'Parcela CDC Actros 30/36',
    tipo: 'Saída',
    valor: 4900.00,
    status: 'Pago',
  },
  {
    id: 'tx-13',
    data: '2026-05-16',
    placa: 'TORK-5C12',
    categoria: 'Combustível',
    empresaFavorecido: 'Posto Graal Sul',
    descricaoHistorico: 'Abastecimento Combo Diesel',
    tipo: 'Saída',
    valor: 2800.00,
    status: 'Pago',
  },
  {
    id: 'tx-14',
    data: '2026-05-28',
    placa: 'TORK-5C12',
    categoria: 'Peças',
    empresaFavorecido: 'Distribuidora TorkPeças',
    descricaoHistorico: 'Kit de Pastilhas de Freio Dianteiro',
    numDocumento: 'NF-10293',
    tipo: 'Saída',
    valor: 1450.00,
    status: 'Pendente',
  },

  // TORK-9D78 Transactions
  {
    id: 'tx-15',
    data: '2026-05-15',
    placa: 'TORK-9D78',
    categoria: 'Frete (Entrada)',
    empresaFavorecido: 'Delta Máquinas Ltda',
    descricaoHistorico: 'Frete Colheitadeira Exportação - CTE 99511',
    numDocumento: '99511',
    tipo: 'Entrada',
    valor: 29800.00,
    status: 'Pago',
  },
  {
    id: 'tx-16',
    data: '2026-05-22',
    placa: 'TORK-9D78',
    categoria: 'Combustível',
    empresaFavorecido: 'Posto Iccar Rodo',
    descricaoHistorico: 'Abastecimento Completo',
    tipo: 'Saída',
    valor: 3100.00,
    status: 'Pago',
  },
  {
    id: 'tx-17',
    data: '2026-05-23',
    placa: 'TORK-9D78',
    categoria: 'Salários/Diárias',
    empresaFavorecido: 'Adilson de Souza Filho',
    descricaoHistorico: 'Pagamento de Salário Mensal',
    tipo: 'Saída',
    valor: 4500.00,
    status: 'Pago',
  },
  {
    id: 'tx-18',
    data: '2026-05-30',
    placa: 'TORK-9D78',
    categoria: 'Pneus',
    empresaFavorecido: 'Michelin Rodoviário',
    descricaoHistorico: 'Troca de 2 pneus tração traseira',
    numDocumento: 'NF-4402',
    tipo: 'Saída',
    valor: 5600.00,
    status: 'Agendado',
  },
];

export const INITIAL_ALERTS: MaintenanceAlert[] = [
  {
    id: 'alert-1',
    placa: 'TORK-5C12',
    tipo: 'IPVA',
    descricao: 'IPVA 2026 está atrasado. Regularizar junto ao DETRAN/SEFAZ.',
    status: 'critical',
    dataLimite: '2026-05-10',
  },
  {
    id: 'alert-2',
    placa: 'TORK-3A45',
    tipo: 'IPVA',
    descricao: 'Vencimento da cota única do IPVA 2026 se aproximando.',
    status: 'warning',
    dataLimite: '2026-06-15',
  },
  {
    id: 'alert-3',
    placa: 'TORK-8B90',
    tipo: 'Seguro',
    descricao: 'Renovação do seguro Allianz expira em breve.',
    status: 'warning',
    dataLimite: '2026-06-05',
  },
  {
    id: 'alert-4',
    placa: 'TORK-8B90',
    tipo: 'Manutenção',
    descricao: 'Revisão preventiva de 85.000 km recomendável (Falta 100 km).',
    status: 'critical',
  },
];
